config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  scope '/admin' do
    resources :categories
  end

  get 'articles', to: 'articles#index'

  resources :articles do
    resources :comments
  end

  get 'by_category/:id', to: 'articles#by_category'

  get '/:id', to: 'articles#show'

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 5 }
    validates :slug, uniqueness: true, presence: true, exclusion: {in: %w[signout auth]}
    validates :category_id, presence: true

    before_validation :generate_slug
    belongs_to :category
    accepts_nested_attributes_for :category
    has_many :comments, :dependent => :delete_all

    def to_param
      slug
    end

    def generate_slug
      self.slug ||= title.parameterize
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 2 }
  validates :slug, uniqueness: true, presence: true

  before_validation :generate_slug
  has_many :articles

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= title.parameterize
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :body, presence: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :comments, :dependent => :delete_all

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.photo = auth.info.image
      user.email = auth.info.email
      user.birthday = auth.info.birthday
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "admin01", password: "humanswilldie", except: [:index, :show, :by_category]
  before_filter :article, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, only: [:new, :create, :edit, :update]
  before_action :get_category_links, only: [:show, :index, :by_category, :edit, :update, :new, :create]

  def index
      @articles = Article.where("publish_time <= ?", Time.now).order('publish_time DESC').page(params[:page]).per_page(5)
  end

  def new
      @article = Article.new
  end

  def create
      _article = params.require(:article).permit(:title, :body, :description, :youtube_id, :image_link, :category_id, :publish_time)
      @article = Article.new(_article)

      if @article.save
          redirect_to @article
      else
          render 'new'
      end
  end

  def show
  end

  def edit
  end

  def by_category
    category = Category.find_by_slug!(params[:id])
    @articles = Article.where(:category_id => category.id).where("publish_time <= ?", Time.now).order('publish_time DESC').page(params[:page]).per_page(5)
  end

  def update
      if @article.update(params.require(:article).permit(:title, :body, :description, :youtube_id, :image_link))
          redirect_to @article
      else
          render 'edit'
      end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

private

  def article
    @article = Article.find_by_slug!(params[:id])
    @category = @article.category
  end

  def get_categories
    @categories = Category.all.map { |category| [category.title, category.id] }
  end

  def get_category_links
    @category_links = Category.all.order('created_at ASC')
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    http_basic_authenticate_with name: "admin01", password: "humanswilldie"
    before_filter :category, only: [:edit, :update, :destroy]
    before_action :get_category_links, only: [:index, :edit, :update, :new, :create]


    def index
      @categories = Category.all.order('updated_at DESC')
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(params.require(:category).permit(:title, :description))

      if @category.save
        redirect_to action: 'index'
      else
        render 'new'
      end
    end

    def edit
    end

    def update
      if @category.update(params.require(:category).permit(:title, :description))
        redirect_to action: 'index'
      else
        render 'edit'
      end
    end

    def destroy
      @category.destroy
      redirect_to action: 'index'
    end

    private

    def category
      @category = Category.find_by_slug!(params[:id])
    end

    def get_category_links
      @category_links = Category.all.order('created_at ASC')
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if current_user
      @article = Article.find_by_slug!(params[:article_id])
      @comment = @article.comments.new(comment_params)
      @comment.user = User.find_by_uid(current_user.uid)
      @comment.save
    end

    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_articles.html.erb
<% @articles.each do |article| %>
    <div class="row article">
      <div class="titles">
        <h1><%= link_to article.title, article_path(article) %></h1>
        <h4 class="subheader"><%= link_to article.description, article_path(article) %></h4>
      </div>
      <% if article.youtube_id.empty? %>
          <%= link_to image_tag(article.image_link), article_path(article) %>
      <% else %>
          <iframe width="100%" height="495" src="//www.youtube.com/embed/<%= article.youtube_id %>" frameborder="0" allowfullscreen="">
          </iframe>
      <% end %>
      <div class="article-body">
        <% if article.category.presence %>
            <span class="label"><a href="/by_category/<%= article.category.slug %>">Kategori: <%= article.category.title %></a></span>
        <% end %>

        <span class="label success">Publicerad för <%= time_ago_in_words(article.publish_time) %> sen</span>
        <% if article.created_at != article.updated_at %>
            <span class="label alert">Senast uppdaterad för <%= time_ago_in_words(article.updated_at) %> sen</span>
        <% end %>

        <div class="row">
          <div class="small-12 columns">
            <div class="article-main-text"><%= auto_link(simple_format(article.body), :html => { :target => '_blank' }) %></div>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div class="row">
  <div class="small-12 columns paginate">
    <div class="small-4 column">
        <% if @articles.previous_page %>
            <h3><%= link_to "< Föregående", params.merge(page: @articles.previous_page) %></h3>
        <% end %>
    </div>

    <div class="small-4 column">
      <% if @articles.current_page == 1 %>
        <h5>Don't forget, you're awesome</h5>
      <% elsif @articles.current_page != @articles.total_pages %>
        <h5>Bara <%= @articles.total_pages - @articles.current_page %> sidor kvar :)</h5>
      <% end %>
    </div>

    <div class="small-4 column text-align-right">
      <% if @articles.next_page %>
          <h3><%= link_to "Nästa >", params.merge(page: @articles.next_page) %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:</h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title, 'Titel' %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :description, 'Underrubrik' %><br />
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.label :body, 'Artikelns innehåll' %><br>
      <%= f.text_area :body, size: '62x12' %>
    </p>

    <p>
      <%= f.label :youtube_id, 'Youtube-id (11 tecken)' %><br />
      <%= f.text_field :youtube_id %>
    </p>

    <p>
      <%= f.label :image_link, 'Länk till en bild för artikeln' %><br />
      <%= f.text_field :image_link %>
    </p>

    <p>
      <%= f.label :category_id, 'Väl en existerande kategori' %>
      <%= f.select(:category_id, options_for_select(@categories)) %>
    </p>

    <p>
      <%= f.label :publish_time, 'När ska artikeln publiceras (lämna tomt för direkt)' %>
      <%= f.datetime_select :publish_time %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/articles/by_category.html.erb
<%= render 'articles' %>

app/views/articles/edit.html.erb
<h1>Ändra artikel</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'articles' %>

app/views/articles/new.html.erb
<h1>Ny artikel</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% @title = @article.title %>
<% @og_image_url = @article.youtube_id.empty? ? @article.image_link : "http://img.youtube.com/vi/#{@article.youtube_id}/0.jpg" %>
<% @og_subtitle = @article.description %>
<div class="row article">
  <div class="titles">
      <h1><%= @article.title %></h1>
      <h4 class="subheader"><%= link_to @article.description, article_path(@article) %></h4>
  </div>
  <% if @article.youtube_id.empty? %>
      <%= image_tag(@article.image_link) %>
  <% else %>
      <iframe width="100%" height="495" src="//www.youtube.com/embed/<%= @article.youtube_id %>" frameborder="0" allowfullscreen="">
      </iframe>
  <% end %>
  <div class="article-body">

    <div class="small-6 column share">
      <%= link_to 'Dela på facebook', 'https://www.facebook.com/sharer/sharer.php?u=' + request.original_url, {class: 'button facebook', target: '_blank'} %>
    </div>

    <div class="small-6 column share">
      <%= link_to 'Dela på twitter', 'https://www.twitter.com/share?u=' + request.original_url, {class: 'button twitter', target: '_blank'} %>
    </div>
    <div class="small-12">
        <% if @category.presence %>
            <span class="label"><a href="/by_category/<%= @category.slug %>">Kategori: <%= @category.title %></a></span>
        <% end %>

        <span class="label success">Publicerad för <%= time_ago_in_words(@article.publish_time) %> sen</span>
        <% if @article.created_at != @article.updated_at %>
            <span class="label alert">Senast uppdaterad för <%= time_ago_in_words(@article.updated_at) %> sen</span>
        <% end %>
    </div>

    <div class="row">
        <div class="small-12 columns">
            <div class="article-main-text"><%= auto_link(simple_format(@article.body), :html => { :target => '_blank' }) %></div>
        </div>
    </div>

    <div class="row">
      <div class="small-12 columns">
        <% if @article.comments.count == 0 and current_user %>
            <h2>Bli den första att kommentera!</h2>
        <% elsif @article.comments.count == 0 %>
            <h2>Logga in för att skriva en kommentar!</h2>
        <% else %>
            <h2>Kommentarer (<%= @article.comments.count %>)</h2>
        <% end %>

        <% @article.comments.each do |comment| %>
            <div class="comment">
                <p>
                  <strong><%= comment.user.name %></strong>, för <%= time_ago_in_words(comment.created_at) %> sedan
                </p>

                <p>
                  <%= auto_link(simple_format(comment.body), :html => { :target => '_blank' }) %>
                </p>
            </div>
        <% end %>

        <% if current_user %>
            <%= render "comments/form" %>
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited
            this article from being saved:</h2>
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title, 'Titel' %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :description, 'Beskrivning av kategorin' %><br />
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Ändra kategori</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
    <div class="row">
        <p><%= category.title %><br />
        <%= category.slug %>, Senast uppdaterad: <i><%= category.updated_at %></i></p>
        <%= link_to 'Editera kategori', edit_category_path(category)%>
    </div>
<% end %>
<br />
<br />
<%= link_to 'Ny kategori', new_category_path %><br />
<%= link_to 'Till startsidan', root_path %>

app/views/categories/new.html.erb
<h1>Ny kategori</h1>

<%= render 'form' %>

<%= link_to 'Tillbaka', categories_path %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      Kommentera som <strong><%= current_user.name %></strong>
    </p>
    <p>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit 'Skicka', {'class' => 'button tiny'} %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= @title %> - <%= "Uppskattat.se" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <meta property="og:image" content="<%= @og_image_url %>">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="256">
    <meta property="og:image:height" content="256">
    <meta property="og:description" content="<%= @og_subtitle %>">
  </head>

  <body>

  <div class="contain-to-grid sticky">
    <nav class="top-bar" data-topbar data-options="sticky_on: large">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Uppskattat.se", root_path %></a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <% if current_user %>
              <li class="name"><a>Inloggad som <strong><%= current_user.name %></strong>!</a></li>
              <li><%= link_to "Logga ut", signout_path, id: "sign_out" %></li>
          <% else %>
              <li><%= link_to "Logga in med Facebook", "/auth/facebook", id: "sign_in" %></li>
          <% end %>
        </ul>

        <!-- Left Nav Section -->
        <ul class="left">
          <% @category_links.each do |category| %>
            <li><a href="/by_category/<%= category.slug %>"><%= category.title %></a></li>
          <% end %>
        </ul>
      </section>
    </nav>
  </div>

    <div class="row">
    <div class="large-12 columns">
        <%= yield %>
    </div>
    </div>
  <%= javascript_include_tag "application" %>

  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-50621093-1', 'uppskattat.se');
      ga('send', 'pageview');

  </script>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Uppskattat.se</h1>